### ISSUE TITLE
parity-signer:: password derived  based account, how to use in polkadot js extension?

### ISSUE THREAD

**Issue by icanfly** [paritytech/parity-signer#1000]
I used the derived path of Polkadot parity wallet (and added the derived password). Now my account is used in other Polkadot ecological chains (participating in crowdfunding on parallel), and then I got the token reward on parallel chain. However, when I wanted to transfer the token on parallel chain, I found that Polkadot JS wallet asked me to process the parity signer. At the same time, Polkadot JS wallet does not support derivation based on password path. It says "/ / / password not supported for 'derivation'. How can I make my wallet address derived based on password available to other ecological chains

**Comment by icanfly** [comment]
resolved

**Comment by seven7e** [comment]
Hey I came across your post when searching for an issue similar to you. I'm also using parity signer (now rebranded as polkadot vault) with parachains and I can't even sign the transaction on a parachain because the following two accounts seem different:
1. a new derived key added in parity signer (offline wallet) on the target parachain
2. the address that's somehow automatically calculated when executing a cross-chain transfer from the relay chain to a parachain

I think the case may be similar to yours as your rewards from crowdloan will be deposited to the "same" address as your Polkadot address, which seems different from the private key created on the parachain in the offline wallet with the same key set (i.e. same private seed)?

Thanks in advance
