### ISSUE TITLE
Metadata issue since v0.9.19 update

### ISSUE THREAD

**Issue by Luft365** [paritytech/parity-signer#1031]
Having issues with PS since the update to v0.9.19. 

Trying to execute any type of transaction gives the following error message: 

"Error! Failed to decode extensions. Please try updating metadata for polkadot network. Parsing with polkadot9180 metadata: 
Network spec version decoded from extensions (9190) differs from the version in metadata (9180). Parsing with polkadot9170 metadata: Network spec version decoded from extensions (9190) differs from the version in metadata (9170)."

I have tried fixing the issue by updating the metadata in PS by scanning the QR code given here: https://metadata.parity.io/#/polkadot

Not sure if I have successfylly added the new metadata in PS, because when I check under network details for Polkadot it still says version 9170 and 9180. 

When trying to add the metadata again PS says: 
"Error! Bad input data. Exactly same network specs for network polkadot with encryption sr25519 are already in the database. "

I have version: 5.0.1

Whats wrong and how do I proceed from here?

Thank you.

**Comment by varovainen** [comment]
Try scanning animated QR in your link.

Looks like you have added network specs instead of the network metadata. Metadata QR is huge multi-frame one, loading it takes a while, you can't miss it. I suppose you have pressed `add to Signer` thing, correct? This means add the network to Signer, in case you don't have it added (and you do, so no need to do it again).
Errors you are getting are just this: at first, no correct metadata version (it needs 9190); then adding already known network.

**Comment by Luft365** [comment]
You're right, I just pressed the add to signer button and scanned a QR code that showed up. 

Scanning tha frames in the animated QR added the metadata correctly. 

Thank you!
