### ISSUE TITLE
Add Polkadot support

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity-signer#113]
Version 1: support for account management & signing arbitrary messages
Version 2: ability to decode a message and display what it does on the screen before signing

Useful resources:
- [polkadot.js](https://github.com/paritytech/polka-ui/blob/master/src/polkadot.js) in polka-ui repo

- keyring (allows creating, import, of keys and allows them to be used for signing, encryption, etc) - https://github.com/polkadot-js/util/tree/master/packages/util-keyring - `@polkadot/util-keyring` on npm

- extrinsics-codec (allows encoding (&soon decoding) of extrinsics) - https://github.com/polkadot-js/types/tree/master/packages/extrinsics-codec - `@polkadot/extrinsics-codec` on npm

**Comment by 5chdn** [comment]
For Polkadot accounts and transactions? Are they much different from Ethereum accounts?

**Comment by jacogr** [comment]
Spoke to Bjorn already, the Js libs for Polkadot won't help much - React native as I remember with Rust backend. So for the keyring -

https://github.com/paritytech/polkadot/tree/master/substrate/keyring

(subkey may be worth a look as well to understand generation)

Important to note on the ed25519 seeds, they are actually the private keys, i.e. `Vec<u8; 32>` - it would be nice to support phrases, either taking them and applying the bake2 hashing and then using that or following the same "hash for x rounds" as currently done for ETH. So basically you would take the seed words, apply some transformations to get to 32 bites and then move from there.

JS/Rust libs does have all the extrinsic encoding/decoding, which I would not suggest doing from scratch again - re-use either the JS tuff (if applicable) or the Rust slicables (if applicable). Since `author_submitExtrinsic` has the actual public or private extrinsics encoded (sometimes sub-encoded, i.e. proposal encodes a private extrinsic as a body).

Use for the rReact part would be (I guess) only `<IdentiIcon />` from `@polkadot/ui-react`

Ok, my braindump done - ask anything on Riot if you want to walk through.

**Comment by maciejhirsz** [comment]
Couple questions here:

1) Do we want the same phrase to private key scheme as we do on Ethereum? I don't know what the constraints are for the ed25519 curve (secp256k1 have to be numbers larger than 0 and smaller than `some really large number starting with a bunch of Fs that I am too lazy to look up`), but assuming it's different, there might be a small deviation on private keys created from phrases.
2) Do we want to continue with the hashing scheme, or fall back to BIP39 (or something like it)? My understanding is that the scheme we are using doesn't actually give us any extra security over BIP39. There is the extra user friendliness of being able to convert any string to a private key, but that is rather dangerous since humans are terrible entropy generators so we mostly stick to the autogenerated phrases from a wordlist anyway. Bruteforcing a BIP39 phrase is of the same complexity as bruteforcing a 256bit private key. Am I missing anything?

Everything else should be fine. We will need to pull in extra crypto since it's a different curve, and the addresses are using a different scheme. There is already a plan to prefix ethereum addresses with `ethereum:` to make them URI compatible, so I reckon doing the same for polkadot from start would be fine. The UI might need some sort of an indicator between Ethereum-like and Polkadot networks.

**Comment by Tbaut** [comment]
This is the main feature for v3. Closing in favour of https://github.com/paritytech/parity-signer/issues/155

>Do we want to continue with the hashing scheme

After discussion, we want to switch to BIP39, it's the second goal of v3. This is logged https://github.com/paritytech/parity-signer/issues/154
