### ISSUE TITLE
Adding new network logos to Parity Signer

### ISSUE THREAD

**Issue by richcsy** [paritytech/parity-signer#1440]
Working with a Parachain that needs this.

**Comment by Dmitry-Borodin** [comment]
That was implemented, right? @krodak @montekki

**Comment by krodak** [comment]
@richcsy current iOS version of Polkadot Vault (aka Parity Signer) includes logos for all parachains featured [here](https://metadata.novasama.io/) and [here](https://metadata.parity.io/), does this cover your parachain or not? 
If not, feel free to get in contact with us and we'll add your parachain logo, we just need svg and test QR code with chain specs to make sure our internal mapping will fit chain specification in QR code for your parachain

**Comment by wilwade** [comment]
@krodak It is missing several from the list here: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot.api.onfinality.io%2Fpublic-ws#/parachains

Should people put up a PR to add it to `android/src/main/res/drawable` and `ios/PolkadotVault/Resources/ChainIcons.xcassets` if they want to add one?

**Comment by Dmitry-Borodin** [comment]
@wilwade for android there is a manual mapping in io/parity/signer/components/networkicon/NetworkIcon.kt:94
So add icon + update mapping. Or ping me and I will update mapping.

**Comment by wilwade** [comment]
Sounds good. I feel like this issue can be resolved @richcsy (as we were the parachain he was referring to)

**Comment by Dmitry-Borodin** [comment]
@rlaferla this logic for android is in io/parity/signer/components/networkicon/NetworkIcon.kt:94
You can see all known icons there.
Preferred format is android vector drawable - android studio can create it from SVG - but it shouldn't be like svg that have PNG resource blob inside et.c. -) as you see there 2 icons added as PNG because their SVG is more complex.
Icons are 56*56
Note it takes string from network logo field, not network name. For some networks those are different.

**Comment by rlaferla** [comment]
Thanks.  How should I submit this?

**Comment by rlaferla** [comment]
https://github.com/paritytech/parity-signer/pull/1845
