### ISSUE TITLE
Secure Enclave to encrypt accounts on iOS

### ISSUE THREAD

**Issue by maciejhirsz** [paritytech/parity-signer#222]
Following #217. We cannot use the private keys or the encryption scheme for signing transactions, but we can use the private key generated by the enclave to encrypt and decrypt the account keystore files.

Use https://github.com/paritytech/react-native-secure-storage

**Comment by hanwencheng** [comment]
I am trying to understand this private key and its related issue.

> We cannot use the private keys or the encryption scheme for signing transactions
You mean we should not directly access it? What is the `encryption schema` here?

Currently, we are using the Account data and Pincode [together](https://github.com/paritytech/parity-signer/blob/master/rust/signer/src/lib.rs#L153) to encrypt and decrypt the private key, is that correct?

**Comment by hanwencheng** [comment]
After discussion with @maciejhirsz  @kirushik and @geastwood , I mark a secure key storage proposal on this [gist page](https://gist.github.com/hanwencheng/736cc28834a06d9cbd4198c03a7c6033), this issue is challenging to me, I have to do more research than I expected, please feel free to leave comments and suggestion, I will continue working on filling more planned implementation details.

**Comment by hanwencheng** [comment]
We are now using Rust runtime to box the private key.
