### ISSUE TITLE
Unable to scan QR codes

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/parity-signer#245]
When I try to use "Scanner" to scan the QR code image of an Ethereum address that is generated from etherscan to send it some ETH it shows an `Unable to parse transaction error`.

![Screenshot_20190616-164637_Parity Signer](https://user-images.githubusercontent.com/6226175/59560514-90a79600-9056-11e9-9956-21436d4168cb.jpg)
`

**Comment by Tbaut** [comment]
Hey Luke,
Thanks for the issue. Signer is designed to scan transactions, but it is not able to craft a transaction from an address.

This issue however is very interesting in the sense that this highlights a source of confusion. Parity Signer needs a software to create a transaction (such as Fether). Although we could add this feature in the future, the fact that the application would require information such as the account's nonce makes is a little less user friendly. Parity Signer will anyway need a software to broadcast the transaction to the blockchain. What we could definitely do is show a friendlier message if we detect that the user scanned an address rather than a tx. I'll log this as a separate issue.
