### ISSUE TITLE
Shows "Secure" when connected to cellular internet

### ISSUE THREAD

**Issue by phillux** [paritytech/parity-signer#266]
v2.2.1 / iOS / iPhone X

I'm connected to cellular internet and it shows "Secure" in the upper right hand corner. When wifi is connected, it shows "Not secure"

**Comment by Tbaut** [comment]
Related to https://github.com/paritytech/parity-signer/issues/174
We're using a dep ([rn comminuty netInfo](https://github.com/react-native-community/react-native-netinfo)) for this feature that seems unreliatble and will not be maintained long term. IIRC it asks for wifi permissions (at least on android), which is a cause of friction.

I'm for removing this non essential feature altogether. What do you think? (also ping for opinions @maciejhirsz @yjkimjunior  @hanwencheng )

**Comment by hanwencheng** [comment]
I think it would be helpful if we can automatically turn off all the internet connection first when we receive a signing request (with the `SCAN` button), and after sending the signing information the internet connection would start again, because the secure sign makes the most sense when the user starts to receive the request.
But it needs some research to see if it could be done easily and make it behave the same with both Android and iOS, some promising library may have done that like [react offline](https://github.com/rgommezz/react-native-offline).

**Comment by Tbaut** [comment]
Parity Signer is meant to be used offline from the start, and it should remain so. We will not implement any feature to force users to go offline because this is was users must do in order to keep their funds safe. The phone should **never** be online.

Although we keep repeating this, we thought originally that it could be a nice to have, to show if users have forgotten to turn off any connectivity feature on their phone. The reality is that we don't check for bluetooth or NFC, only internet connectivity, which makes it loose its appeal IMO

**Comment by yjkimjunior** [comment]
Agreed with @Tbaut for the most part. IMHO ideally we would block the user from doing anything at all period when any of the above (wifi, bluetooth, nfc) are detected as enabled, or more easier would be to check if airplane mode is enabled. Only then should we let them get to the AccountsList screen.

a) It's unrealistic to expect users to have a "burner" smart phone that is always offline.
b) even if we notify users whether they're secure or not, if someone f's something up using Signer while connected to a network, the burden still falls on us. Saying, "oh but didn't you notice the Not Secure message?" after someone lost money won't gain us any fans. Best to dummy proof from the start.

**Comment by Tbaut** [comment]
> when any of the above (wifi, bluetooth, nfc) are detected as enabled, or more easier would be to check if airplane mode is enabled. Only then should we let them get to the AccountsList screen.

If the user has ever been online or will ever be (not necessarily while using the Signer), this is a threat. 

We should probably show a big warning first when installing Signer, before the T&Cs.

All in all, we're getting away from my original question. Should we remove the "online status" alltogether, or just keep the "not secure" part as suggested in https://github.com/paritytech/parity-signer/issues/174
