### ISSUE TITLE
Double tap needed in scrollview

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#278]
How to reproduce (on Android not sure about iOS):
- recover an account
- tap the "name" field to enter a name.
- top the "next step" button..  you need to tap it twice.

It happens on account creation as well and sometimes when choosing network.

This has been introduced here https://github.com/paritytech/parity-signer/pull/272#pullrequestreview-264780795 and is linked to the use of `ScrollView` and potentially `KeyboardAwareScrollView`. 

I was unlucky trying things like described [here](https://github.com/APSL/react-native-keyboard-aware-scroll-view#android-support), [here](https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/233#issuecomment-379583908) or everywhere on the internet with `keyboardDismissMode` and `keyboardShouldPersistTaps="always"`

This scroll things needs love.

**Comment by hanwencheng** [comment]
The PR LGTM, but one more thing about the workflow of recovering an account, since create a empty account will result in nothing in the storage, I think we should prevent the user enter the pin creation page with empty seed. also according to [the previous discussion](https://github.com/paritytech/parity-signer/issues/127#issuecomment-454595735), related code [here](Basically these situation need to be prevented from further steps.), probably create a new issue to solve this problem.

**Comment by Tbaut** [comment]
While we're playing with the scrollview, it'd be great to make sure that on recovery account, the recovery phrase field is high enough so that we can see the suggestions. BTW the suggestions are also subject to this double tap problem.
