### ISSUE TITLE
Many incorrect or unmet peer dependency warning when installing

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#307]
When running yarn:
```bash
warning " > react-native-markdown-renderer@3.2.8" has incorrect peer dependency "react-native@^0.50.4".
warning " > react-native-secure-storage@1.0.0" has incorrect peer dependency "react-native@^0.40.0".
warning "react-navigation > react-navigation-drawer@1.2.1" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-stack@1.4.0" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-tabs@1.1.4" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "@react-native-community/eslint-config > @typescript-eslint/eslint-plugin@1.12.0" has incorrect peer dependency "eslint@^5.0.0".
warning "@react-native-community/eslint-config > @typescript-eslint/parser@1.12.0" has incorrect peer dependency "eslint@^5.0.0".
warning "@react-native-community/eslint-config > eslint-plugin-react@7.12.4" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0".
warning "@react-native-community/eslint-config > eslint-plugin-react-native@3.6.0" has incorrect peer dependency "eslint@^3.17.0 || ^4 || ^5".
warning "@react-native-community/eslint-config > @typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils@1.12.0" has unmet peer dependency "typescript@*".
warning "@react-native-community/eslint-config > @typescript-eslint/eslint-plugin > tsutils@3.14.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev".

**Comment by geastwood** [comment]
* `react-native-markdown-renderer`: in their package.json they have specified the `peerDependencies` inaccurate, a [PR](https://github.com/mientjan/react-native-markdown-renderer/pull/118) is submitted.

* `react-nateive-secure-storage@1.0.0` specified also inaccurately, however, they have fixed in a newer release. Updating the lib will fix the problem.

* Warnings regarding `react-navigation` is due to the fact, `react-native-screens` is defined as peerDependencies,  however, is not **mention** in your package.json. But it will still work, since yarn will nevertheless install it under `node_modules`. In order to get rid of the warning, just specify in package.json

* And with `react-native-community`, guess the only option is to wait for them to fix.

**Comment by geastwood** [comment]
What does the tag `F5-task` mean?

**Comment by Tbaut** [comment]
Thanks for your help on that. The label `F5-task` helps defining this issue. It's not a feature, a bug fix or a refactor. I'd understand it as "chore".

**Comment by geastwood** [comment]
I could put up a PR. 
* `react-native-markdown-renderer`: wait for the that [PR](https://github.com/mientjan/react-native-markdown-renderer/pull/118) to be merge
* `react-native-secure-storage`: will update the lib to fix the warning
* `react-navigation`: won't do anything, since it's a bit overkill to introduce a lib just to fix the warning
* `react-native-community`: won't do anything

**Comment by Tbaut** [comment]
That would be awesome :)

> `react-native-secure-storage`: will update the lib to fix the warning

This is currently hosted https://github.com/paritytech/react-native-secure-storage I don't know why it was forked and we should check if it's possible to use the originial one instead now.

**Comment by geastwood** [comment]
Interesting, haven't realized it has been forked, thanks for the heads up! I will check the difference and put up a PR.

**Comment by geastwood** [comment]
Replace `react-native-secure-store` should be replaced with more robust/secure [implementation](https://github.com/oyyq99999/react-native-secure-storage). Also refer to this [comment](https://github.com/paritytech/parity-signer/issues/312#issuecomment-520453436).

I think this Issue is almost meaningless since only to wait for the merge of [**react-native-markdown-renderer**](https://github.com/mientjan/react-native-markdown-renderer/pull/118).

**Comment by Slesarew** [comment]
RN removed
