### ISSUE TITLE
Prevent new line for account recovery

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#368]
New lines shouldn't be allowed in the recovery field.

**Comment by jakeols** [comment]
Hey, @Tbaut - was looking for a first issue here and decided this looked good :) 

Simply adding `blurOnSubmit={true}` solves this ([RN docs here](https://facebook.github.io/react-native/docs/textinput#bluronsubmit))

Because `onSubmitEditing` is invalid for multiline fields, it ends up just not doing anything. I can create a PR for this if you want (added it [here](https://github.com/jakeols/parity-signer/commit/c557cdd45f73b7b5b8726e4ad33e1492267e05f5))

**Comment by Tbaut** [comment]
Thanks @jakeols, this definitely make sense. Ideally, we should also detect new lines (in case of a copy/paste) and show an error accordingly as we do for white spaces [here](https://github.com/paritytech/parity-signer/blob/61ad81c06df8078942c39458126d312a0a253bea/src/util/account.js#L75-L80) for instance.

PR made by contributors are very welcome :)

**Comment by jakeols** [comment]
@Tbaut In the case of copy/paste, would it be better to parse and remove newlines? Something like `seedPhrase.replace(/(\r\n|\n|\r)/gm, ' ')` , and then let the validator take care of it after that?

**Comment by Tbaut** [comment]
Sorry for the super late reply. I would automatically remove the line indeed.

ps: hold off for any PR in the next days, a huge refactor is about to be merged and would heavily conflict with anything on its way.

**Comment by Slesarew** [comment]
I do need to check this one in new UI!
