### ISSUE TITLE
Manage metadata screen

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#407]
This page should be available from the top level of the app.
It should:

- show the default networks metadata (Kusama)
- show the added networks metadata with the ability to delete them (no edit for now)
- show the metadata version
- show a "add metadata" button similar to the "Scan" button (bringing to the scanner)

**Comment by yjkimjunior** [comment]
this answers a question of how to make clear the intention to scan metadata as opposed to any other random message clear to the scanner.

on the reading end:
* [ ] - save the current metadata for Kusama, Substrate in `db`
* [ ] - load the metadata from `db`, should be able to query it along with the rest of the `networkSpec`s
* [ ] - button to scan metadata will pass that as a flag in props so that ScannerStore will know not to handle it as a regular message (in which case it would just hash it and try to sign it
* [ ] - construct that Metadata from the concatenated blob
* [ ] - register types
* [ ] - PayloadDetails use the appropriate type registry depending on the `genesisHash` provided in the payload.
  * currently we have a single type registry instance that is injected only once. There could be conflicts and overrwrites now with multiple networks, so need make sure to reset that each time a new payload is scanned.

On the generation end:
* [ ] - UI for easily getting a well formatted QR for Signer to be able to decode it. Input: ws endpoint. Output: QR. In between would call state_getMetadata, strip everything but calls from it, hex encode, then feed the result to @polkadot/react-qr.
* [ ] - UI for browsing supported QRs.

**Comment by Tbaut** [comment]
One thing that is missing here and I'm not sure it's easy to add securely: 
We want to sign the metadata with a "Parity" private key on the QR generation side, and verify this signature on Signer side with a trusted public key.

Fetching metadata and feeding the blob to @polkadot/react-qr doesn't have this step and is therefore quite unsecure if a malicious endpoint is provided or if the node is attacked. 

Your solution has the great advantage of being dynamic, we could eventually modify it to add a signing part that we could do manually each time there's a new network/metadata.

**Comment by Slesarew** [comment]
Not a screen, but this functionality is added.
