### ISSUE TITLE
Scanning Kusama transfer is much slower than Ethereum

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#430]
On my real device scanning a transfer for Ethereum takes ~1sec until it shows the Tx details. Scanning a transfer for Kusama takes much more, 3-5s ?, so that I'm actually super carefully holding my device scanner probably because nothing happens for long, which is probably useless since the scanning part is most probably not the bottleneck (Ethereum QR code is more, or as dense as a Kusama one).

Possible solutions:
- find out what's taking so long on Kusama scanning and fix it if it's not expected
- show a spinner as soon as we have the data from the QR code instead of keeping showing the scanner, to tell the user to stop trying to scan anything.

**Comment by yjkimjunior** [comment]
It is expected to take a bit longer since there is a lot of O(N) operations in the background though it isn't noticeable on the iPhone 6 I'm testing. Ethereum payload is just a straight up JSON with a `publickey` and a 32 byte `rlp` so it's really quick.

but for Substrate, combing through step by step what happens on scan, for a single frame:

1. one pass over the uint8array to strip padding O(N) bounded at 1024 bytes. presumably super quick
2. one pass over the stripped uint8array, with some constant time key value lookups O(1), and base58 encoding the public key. presumably super quick.
3. if account is not found in storage in its current encoding, loop through the existing accounts and encode/decode until match or exhaust the list. Possible bottleneck but unlikely.
4. setUnsignedData, navigate to TxDetails to sign. constant time setter. nothing much happening here.

so that's my lengthy way of saying I'll just add a Spinner.

**Comment by Slesarew** [comment]
Decoding transactions takes time now since they have to be decoded completely every time to prevent #724 . It's not done on rendering thread anymore in #791 and further and QR scanner disappears as soon as decodeable scan is obtained.
