### ISSUE TITLE
Edgeware signing transaction does not work

### ISSUE THREAD

**Issue by carumusan** [paritytech/parity-signer#576]
Says "Could not decode method with available metadata". Pressing Sign Transaction also does nothing.

**Comment by hanwencheng** [comment]
Close it as known issue, should be fixed by #570, the new version 4.1.1 is under approval, android version is available on https://github.com/paritytech/parity-signer/releases/tag/v4.1.1-beta .

**Comment by hanwencheng** [comment]
In addition to that:

Do you have any override type on Edgeware? if there is, then the decoding error is because you types is different from Substrate default type, and either polkadot.js/app or signer understand how  to  decode it.

About extrinsic types: https://polkadot.js.org/api/start/types.extend.html#impact-on-extrinsics


### Solution

Override you own tyopes on polkadot.js [developer pages](https://polkadot.js.org/apps/#/settings/developer). 
in the last part of this [post](https://substrate.dev/recipes/1-prepare-kitchen/2-interact-node.html) it shows a example how to do that.

This could be a walkarond, the better way to do it is to make a PR to polkadot.js and override you types like what we do on Kusama here: https://github.com/polkadot-js/api/blob/master/packages/types/src/known/overrides.ts#L132-L134
then once signer has synced with updated pokadot.js/api, then both polkadot.js/apps and signer will be able to decode it.

**Comment by hanwencheng** [comment]
BTW, what do you mean by  "Pressing Sign Transaction also does nothing."? does the QR code comes?

**Comment by carumusan** [comment]
> BTW, what do you mean by "Pressing Sign Transaction also does nothing."? does the QR code comes?

It doesn't do anything after pressing sign transaction. No QR code.

**Comment by hanwencheng** [comment]
@carumusan does adding types solve the problem?

**Comment by hanwencheng** [comment]
https://github.com/polkadot-js/api/pull/2125 here is an example how to update their types to api.

**Comment by carumusan** [comment]
Version 4.1.1 fixes signing the transaction i.e. Pressing "Sign Transaction" is now functional.
 
However the metadata for the transaction still can't be decoded. I'll check whether I can add the types to fix it.

**Comment by hanwencheng** [comment]
@carumusan please ping again when you get edgeware types registered on Polkadot.js/api, then I will update the related packages to make it shown.
