### ISSUE TITLE
Consider moving technical documentation from  wiki into repo to be in sync with code [suggestion]

### ISSUE THREAD

**Issue by gww-parity** [paritytech/parity-signer#621]
I see great advantage of having technical documentation in sync with code.

Therefore I suggest moving technical things from wiki to markdown files in this github repository, so 

* they can be modified together with code and stay in sync with code.
* also modifications to documentation could be peer reviewed

For "wiki" I would leave non technical things, like some things for end user - what this product is about, philosophy, not technical related staff...

**Comment by gww-parity** [comment]
P.S. If you like idea, please give me green light and assign to me, I am glad to make a task of moving technical documentation from wiki to repo.

**Comment by hanwencheng** [comment]
Hi, @gww-parity  thanks for the suggestion! it was originally together in the `Readme.md` file, wy put it into Wiki is because it is easy to order and update as well.

Whereas it cannot be tracked with different versions, plus in the future we will make some refactor(e.g. extract Rust part into separate project).

would glad to review PR when it is ready.

**Comment by gww-parity** [comment]
Ok, after going through process of setting up environment , I realized that current documentation in "requirements" section does not cover many important aspects, so maybe let's see if we can move it a bit forward first, before moving into this repo.  ( related [#623](https://github.com/paritytech/parity-signer/issues/623) )
