### ISSUE TITLE
The Password input only have the number.

### ISSUE THREAD

**Issue by jiangfuyao** [paritytech/parity-signer#633]
When I create an account with the Optional Password, use the alphabet&number.

But scan QR to transfer, input the Password to unlock account. The keyboard only can input the number. Can't input alphabet.

**Comment by hanwencheng** [comment]
Hi, The Pin code and the Password for derivated account are baiscally two thing.

Pincode: user created for the whole identity, will need to input once for short period of time, it aims for basic security, and easy to control, so only numeric would easy to input.

Password: it is used as additional security layer for specific account. The password will always needed for signing with passworded account, and user could use alphabet&number combination to make it even hard to guess.

So to summary, the pin code most focus on the User experience and offer basic security, whereas password focus on the security. And that's why the password setting methodology is different.

**Comment by jiangfuyao** [comment]
@hanwencheng I want to say that: When the parity-signer account to sign, needs to input the PIN & password.
**BUT:** the keyboard only can input the number. `password` sometimes is `ABCD+Number`

**Comment by hanwencheng** [comment]
thanks for clearify, it is a bug.
