### ISSUE TITLE
One account for multiple networks

### ISSUE THREAD

**Issue by jiangfuyao** [paritytech/parity-signer#655]
Scanning codes will not be recognized for different network accounts now.  

Such as:  
I want to sign a Kusama transaction using a Polkadot account. Scanning the code indicates that there is no such account.  
But their public keys are the same.

**Comment by hanwencheng** [comment]
> I want to sign a Kusama transaction using a Polkadot account. Scanning the code indicates that there is no such account.
But their public keys are the same.

This is a intended behaviour in design, we splits the accounts into different screens in order to manage them separately, which you may also refer to Ethereum Networks Cards, there the account you created in Kovan will not sign transaction in Ropsten.

I suggest to derive new accounts for another networks.

**Comment by jiangfuyao** [comment]
My suggestion is: scan the code to identify the public key to find the account.

**Comment by kirushik** [comment]
@jiangfuyao Sharing the same account across the networks is a bad idea; as such, we don't want to support it in Signer in any form.

You can (and probably should) use different derivations from the same seed phrase for different networks -- is there any particular reason this won't work in your usecase?
