### ISSUE TITLE
App crashes at startup - Android 6.0.1

### ISSUE THREAD

**Issue by vindberg** [paritytech/parity-signer#674]
I have installed the Signer on an older phone (Nexus 5) and it crashes instantly when opening the app. A white screen appears shortly and then the "Parity signer has stopped" message.

Will it ever work on Android 6.01?

Thanks.

**Comment by hanwencheng** [comment]
Hi, it is compatible with Android 6.01, current crash problem on some devices is caused by Rust bindings on v4.4, we are investigating the crashes now, please use v4.3 now.

**Comment by vindberg** [comment]
Thanks for the reply. When do you expect a fix?

I will try the other version if I can get it installed as a pack.

**Comment by hanwencheng** [comment]
I have a Nexus 5 and can reproduce the crash.

It seems to be a rust library building problem because Unwind is not linked correctly in ARM32 architecuture according to the [discussion](https://github.com/android/ndk/issues/289), and [NDK docs](https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md#Unwinding).

It seems we need to add the following flags when building ARM32 in the [build script](https://github.com/paritytech/react-native-substrate-sign/blob/master/scripts/build.sh)
```
-Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libunwind.a
```
but I am not sure, @tomaka do you have any ideas where to add these flags?

![Screen Shot 2020-08-16 at 15 29 34](https://user-images.githubusercontent.com/6014309/90335433-4fea3a80-dfd5-11ea-9dc6-a74347de8e3e.png)

**Comment by hanwencheng** [comment]
#675 current solve the problem, but I use a fallback solution, a optimized way to solve it still need to fix building with prebuilt NKD libraries.
