### ISSUE TITLE
Supported Chains / Coins / Tokens

### ISSUE THREAD

**Issue by SigningSign** [paritytech/parity-signer#706]
Its very hard for people new to the crypto space, to find out which CryptoCurrencies are actually supported in Parity Signer.

On the website it says:
"Support for Ethereum, Ethereum Classic, as well as Kovan and Ropsten networks"
but on the picture beside it, in the wallet there is also Accounts for Polkadot, Kusama, Kulupu etc...
https://www.parity.io/signer/

So, what coins can I securely store on an old phone with parity signer?
Can I store ERC20 tokens?

**Comment by Tbaut** [comment]
Thanks for your Feedback, the website is indeed wrong, many substrate based chains are supported, including Kusama and Polkadot. I will make sure this is changed.

You can use an Ethereum address to store ERC20 tokens, one very big deal though is that the ERC20 tokens will not be clearly displayed. So when doing transfers, you will not be able to verify what you transfer. This is a VERY big problem, because you, the human reading the offline signer screen, are the last defence against a complex attack, cf what happens to this person: https://medium.com/@hugh_karp/nxm-hack-update-72c5c017b48

Therefore I would not recommend storing ERC20 token, although it is intrinsically supported.
