### ISSUE TITLE
Can't sign messages generated by the latest master build of the extension

### ISSUE THREAD

**Issue by FartFeatures** [paritytech/parity-signer#779]
Please see full description here: https://github.com/polkadot-js/extension/issues/741

**Comment by Slesarew** [comment]
There is a PR with this feature supported:
https://github.com/paritytech/parity-signer/pull/773

At the same time, the signer is undergoing deep backend rebuild and that branch might be dropped entirely since transaction processing logic is being replaced completely. The reason for this rehaul is security; please use these old builds at your own risk and discretion.

The feature you request will certainly be included in next official release (which will be major). I'll close this issue when this feature will be included in buildable branch intended (eventually) for release.

**Comment by Slesarew** [comment]
Implemented in #791 and #793
