### ISSUE TITLE
Signer seems not to warn about missing accounts.

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity-signer#79]
This user simply got a new phone and tried to sign a new transaction with it, but there was nothing that told him it's not possible.

https://ethereum.stackexchange.com/questions/25476/parity-signer-qr-code-not-working-stuck-on-parity-signer-pending

**Comment by debris** [comment]
Latest version of mobile application displays the following warnings:

- *No accounts found* - when no accounts has been found on device
- *You are not able to sign transaction X from  + `address`* - when trying to sign transaction with uknown account

[link to the source](https://github.com/paritytech/parity-signer/blob/091a3e07a985239254e85f4adf100a149eeb9010/src/actions/scanner.js#L85-L95)

@5chdn should we rewrite those messages? should we have any additional?

*those messages are only available for iOS (due to various complains from apple). Android version has not been published yet

**Comment by 5chdn** [comment]
No, if future android versions will include this messages, we can consider this closed.
