### ISSUE TITLE
Issues with deriving accounts from seed generated in Signer or Polkadot.js 

### ISSUE THREAD

**Issue by YUSHLD** [paritytech/parity-signer#817]
Hi,

I am having some issues recovering a Kusama account using Signer. 

When I enter the seed phrase when recovering the account I get the following error message: "the recovery phrase is not a valid BIP39 seed and will be treated as a parity brain wallet" and am presented with a option to proceed or go back. If I proceed I am unable to derive an account from the seed. The following error message pops up and Signer crashes: "cannot derive account from seed: substrate address cannot be generated please check suri and prefix".

The seed phrase I entered was generated using either Signer or Polkadot.js. I haven't been able to find anything on this issue (sorry if this is due to ignorance on my part). 

Anything you could do to help?

Thanks

**Comment by Slesarew** [comment]
This often means wrong number of words and/or words outside of standard dictionary. If the phrase was generated by older Signer version, it might be "legacy" account support for which was effectively dropped long time ago (they are still probably recoverable/usable on older versions of Signer, something like v3.* or so). Otherwise, check number of words (typically 12 or 24, a few other larger numbers are possible) and spelling, capitalization. Typical seed phrases and general specifications could be found [here](https://substrate.dev/docs/en/knowledgebase/integrate/subkey)

Which version of Signer are you using?

We will be rolling out new version of Signer in some months, if what you are describing is related to the Signer itself, it might go away on its own; otherwise we will have to figure out what is happening. Either way, please let me know if what I suggested helps.

**Comment by YUSHLD** [comment]
It is a 12 word seed phrase. I suspect it is a legacy account. How can I obtain or access older versions of Signer? I am using 4.5.3 beta. (Unfortunately, waiting a few months is problematic.)

Thanks

**Comment by kirushik** [comment]
@YUSHLD If you're on Android, you can try sideloading APK from https://github.com/paritytech/parity-signer/releases/tag/v3.0.11-beta
Unfortunately, the easiest way to install a custom version of app for iOS is to build and sideload it yourself. (Or just get aceess to an Android phone for a while).

As usual: please be extremely careful, update the phone to the latests OS before installing the app, only ever use full-disk encrypted devices, don't input your keys into a device which is online, and factory-reset it before setting Signer up and after you no longer need it or the keys in it.

**Comment by YUSHLD** [comment]
That is quite complex and seems that sideloading is quite insecure. Are there any alternatives for dealing with this issue?

Thanks again for the help!
