### ISSUE TITLE
Invalid Address Generated for Parallel Finance

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/parity-signer#876]
Reproduction Steps:

* go to: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.parallel.fi#/settings/metadata
* scan this metadata into signer
* a new root account is generated
* Back in polkadot JS, try to import the account
* It has an invalid checksum

> Decoding JDK5nNGcVwsA4zJDfL7S9y9UCxgQVYRjVA4NSJ43ajCkvDhU: Invalid decoded address checksum

**Comment by Slesarew** [comment]
Is it Signer from store or internal testing version?

**Comment by Slesarew** [comment]
Store Signer has a known issue with base58 management - it just doesn't work properly, there is some serious work needed to fix it properly.

The new prototyping version should not even accept that QR code (and it is not metadata, only stable network specifications). To add new network, try this crate: https://github.com/paritytech/parity-signer/tree/backend-atomize-db-and-certificates-policy/rust/generate_message (note that usable version is not in master yet, but it conforms to specs of the testflight version, unlike whatever is in master at the moment)

**Comment by Slesarew** [comment]
![add_specs_parallel-sr25519_unverified](https://user-images.githubusercontent.com/33295157/141253100-c56d6f15-500d-4874-80be-9bde3e0adb7b.png)

This is an example of that network's specs for new signer I've just made through that crate (unsigned so that it's easy to test and remove - they could be reversibly removed with no consequences as long as they are not signed, but of course should not be trusted this way nor used in production); you'll need metadata generated to actually use that network.

**Comment by shawntabrizi** [comment]
> Is it Signer from store or internal testing version?

It is the signer from the store, not the new signer from internal testing.

Indeed there seems to be an issue with ss58 management.

**Comment by Slesarew** [comment]
It's a small mess there. Could be fixed but I won't since it's far from it's worst problem.

**Comment by Slesarew** [comment]
unsupported version
