### ISSUE TITLE
Unable to parse QR data: Scanned QR should contain either extrinsic of a message to sign

### ISSUE THREAD

**Issue by ddaws** [paritytech/parity-signer#881]
I am getting an error when attempting to sign the verification message required to participate in the Moonbeam crowdloan. I am not trying to participate in the crowdloan, I am just trying to understand how the Parity Signer works.

App version: 4.5.3 for Android

Any help understanding why the Parity Signer cannot sign the transaction is appreciated. Thank you :pray:

**Comment by Slesarew** [comment]
Thanks for the interest.

The principle behind Signer is quite primitive: it signs fixed portion of the payload it receives. That said, there are several types of payloads and Signer identifies which type it received before signing it and only signs if it has information on which portion to sign and how. One byte in the prefix of payload encodes transaction type.

4.5.3 only supports calls within Substrate networks; that is, payloads that could be decoded as calls. AFAIK Moonbeam crowdloan participation messages are not those - they are just messages, that could be decoded as plaintext in unicode. Support for this type of payloads was just added to development version this year (although it's really trivial addition, the system still has to be designed properly so that there would not be a possibility to disguise proper payload as a message accidentally - which requires proper decoding of all payloads).

You can read more about transaction format [here](https://github.com/maciejhirsz/uos)

**Comment by ddaws** [comment]
@Slesarew is there a public roadmap indicating when a new version with support for signing generic messages will be released? Or would the team be open to releasing this in a minor or patch release?

**Comment by Slesarew** [comment]
I've just populated milestones with more or less current expected roadmap today; one of them has a milestone. All non-legacy development code has this support at the moment, including master branch and latest "release candidate" build (although they are currently in testing and thus not safe to use - although they are not much worse that what is available in stores at the moment in this aspect. The published build was also built with CI tools, not in proper building environment, which means it is also in supply chain attack danger zone. Use for testing only!)

**Comment by ddaws** [comment]
Thank you, this all makes sense. 

How is the Parity Signer funded? Can I buy you a beer or a coffee?
