### ISSUE TITLE
Support of other KSM networks

### ISSUE THREAD

**Issue by ssfking** [paritytech/parity-signer#886]
Hi there, is it possible to add custom KSM networks like Kilt that just completed the KSM crowdloan? I am unable to sign transactions in the Kilt network using my KSM account in the Parity Signer app right now. Thanks

**Comment by Slesarew** [comment]
Not to Signer currently in stores. Signer in master branch can do it through use of /rust/generate_message tool

**Comment by carltraveler** [comment]
when does the new verison released. it will support other parachain?. I think many people in the polkasystem use parity-signer as a hardwallet.

**Comment by Slesarew** [comment]
It should fully support parachains, although I'm not fully certain until I get enough testers reports on their experience with generating and using Signer update messages.

Yes, new version will require removal of the old one; this is the only proper way to update the code for Signer. There is at least one more hard breaking *planned* update in future which will significantly improve app's usability - #898 will allow on-chain verification of network information known by Signer. But the whole point now is to minimize number of re-installs since they are complicated indeed.

Also, nobody should rely solely on Signer to store keys, since it is just a phone after all, and those break. You should keep some kind of seed phrase backup at all times and be ready to restore from it. Thus we are trying to simplify restoration flow as much as possible too, but that's subject of research now.

**Comment by carltraveler** [comment]
thanks for patient answer. great work. appreciate that

**Comment by Slesarew** [comment]
unsupported version
