### ISSUE TITLE
when will be version 5 release? I cannot sign Astar network in the latest version 4.5.3 :(

### ISSUE THREAD

**Issue by ccfiel** [paritytech/parity-signer#912]

**Comment by Slesarew** [comment]
iOS release is now staging in AppStore; Android will take couple more weeks, you can try to build temporary replacement  yourself at your own risk using `android-not-broken` branch if you like.

Now this network you mention is not among the defaults, see if you can install it in new Signer using https://github.com/paritytech/parity-signer/tree/master/rust/generate_message tool, let me know if you encounter problems.

**Comment by ccfiel** [comment]
So what I will do is run this first https://github.com/paritytech/parity-signer/tree/master/rust/generate_message and then build android-not-broken branch?

**Comment by Slesarew** [comment]
Hmm, in general yes, but there might be small incompatibility between generate-message format between these branches - you'll encounter that when adding network specifications probably - so you might need to use generate_message from that branch as well.

Also, there is a draft tagged test pre-release 4.6.6 that you can try; it's built outside of proper clean room and is thus not safe to use, but you can try that as well instead of building android yourself. All these options carry certain risks, and Signer is still beta. Please be careful and back everything up.

Also remember that it is recommended to factory-reset the phone before installation of new Signer version; at any rate, there should not be previous Signer installed when you install it, this is not handled anywhere and will break things since it should not be done anyway.

**Comment by ccfiel** [comment]
I did try 4.6.6 but it's a total revam. So I do not have to add every network? Because the old one you have to add every account in network.

**Comment by Slesarew** [comment]
You get only few networks with some default keys automatically (people were getting confused about derivations, now you just see how that works); then you add whatever networks and keys you like - yourself. 5.0.0 allows adding derivations through template QR generated on any untrusted machine, but 4.6.6 still does not have that.

**Comment by alindece** [comment]
also i can't sign ASTAR network - createType(ExtrinsicSignature):: Cannot map Enum JSON, unable to find '0xsubstrate:

**Comment by GalioColossus** [comment]
For now better use stylo. Astra network is already added https://github.com/stylo-app/stylo/issues/21

**Comment by alindece** [comment]
I'm trying with Stylo but it still gives me an error.
If I read the qr code with the phone:
"Unable to parse QR data"
If I do read the QR code from the phone:
createType (ExtrinsicSignature) :: Cannot map Enum JSON, unable to find '0xsubstrate: xxxxxxxxxxxxxxx: polkadot' in ed25519, sr25519, ecdsa

**Comment by ccfiel** [comment]
@alindece I do not know your problem but I was able to sign a transaction using stylo. I know it's working. Did you add a new account and select astar network?

**Comment by alindece** [comment]
No, I have recovered an existing account, on ASTAR I used an address created on polkadot and enabled on all chains
In this case I tried to do the recovery from the seed phrase
1)recovering on polkadot network and trying to sign it ASTAR (error)
2)recovering on polkadot network and then changing chain on ASTAR and tried to sign (error)
3)recovering on ASTAR network and trying to sign (error)

**Comment by Slesarew** [comment]
Ok, I'm closing this. 5.0.0 is out for iOS anyway and Astar works nicely there as far as I can tell. Now to add Astar there, someone trustable should generate an update (I won't do it for the same reason I don't build releases of Signer). One place where centralized updates will be posted as more are checked and signed is https://metadata.parity.io/ if you are into centralized things. Otherwise, literally anyone can make an update using `generate_message` tool. If you can't figure out how - please rely on somebody who can: network maintainers, substrate developers, your community, etc - but don't go trying things randomly; Signer is an advanced tool for users who need extra security, it has steep learning curve and has some inconvenience in usage compared to js extension. Using any airgapped tool incorrectly gives false sense of security instead of safety, airgap is not magic, it can be breached without proper usage practices.

>No, I have recovered an existing account, on ASTAR I used an address created on polkadot and enabled on all chains

This most probably is a result of networks isolation in Signer - you can only have each key in 1 network in versions prior to 5.*; this is no longer true in 5.0.0 - although you'll have to explicitly add key to all networks where it is needed (hopefully error messages should guide you there now, let's see how clear it is). I know, it was confusing, lots of people got lost there and that's why I've changed this.

**Comment by Tbaut** [comment]
Thanks a lot @Slesarew, congrats for the launch. I'm looking forward to see it on Android as well.
Would you mind having some documentation regarding the `generate_message` tool? I believe it should be as accessible as possible so that ppl don't have to trust anyone else doing it for them.
