### ISSUE TITLE
Off by one issue with progress bar when scanning multipart gif

### ISSUE THREAD

**Issue by pepyakin** [paritytech/parity-signer#920]
When reading one of those metadata gifs I noticed that the progress bar may overshoot. For example, with a gif with 250 parts the scanning would finish when read either 251 or 252 parts.

That's on iOS with the App Store version.

**Comment by Slesarew** [comment]
This is inevitable - raptor erasure codes have probabilistic nature, there is some chance that you'll need slightly more frames. Although the number shown now is an estimate either way, we can tweak it up or down a bit. Maybe we should bump it up a few numbers, just to lower expectations?

**Comment by pepyakin** [comment]
I guess.

Can't we use percentage though?

**Comment by Slesarew** [comment]
We can, but then we'll have something like "101%" in unfortunate cases, which is worse I suppose; and we can't predict how many frames are needed because it depends on which frames are captured next. I had % in early drafts of this interface, frame count *feels* more informative somehow.

**Comment by pepyakin** [comment]
> We can, but then we'll have something like "101%" in unfortunate cases,

It's not necessary though: the label can be clamped to 0-100% or even 0-99%.

**Comment by Slesarew** [comment]
>clamped to 0-100% or even 0-99%

That would not be informative though; I've seen once a corrupted transaction that just did kept counting frames; without proper indication just how much extra frames were caught, this would cause user to suspect that every video that slowed down near completion is corrupt and cause needless frustration, especially as metadata size grows. We should eventually discover some optimal mechanism to auto-reset failed transactions, but that should be based on more testing and measurement and probably on user research.

Maybe we should indicate better that target frame count is just an estimate? @goldsteinsveta

**Comment by goldsteinsveta** [comment]
I'd suggest
- to keep the frame count
- add % as a subtitle, clamped to 99%, same for the width of the bar
- add units to what we measure with frame count and percentage, so that 252/251 does not look too weird and 98% does not overpromise how soon the scanning will be done.

<img width="320" alt="ContextMenu - Key" src="https://user-images.githubusercontent.com/8782596/153062008-06d95754-abd3-4007-86b5-168c13c380d8.png">

Happy to learn more about the QR movies to replace the placeholder strings!

**Comment by Slesarew** [comment]
> add % as a subtitle
@goldsteinsveta  I liked the idea initially, but now I just realized that this is showing too much to user without really telling anything new - it's 3rd indicator for the same value on screen.

Indeed, the probability of parsing whole payload at exact number of frames is about 99.5%, by bumping required number by 1 we increase it about 2 digits, to 99.99998*% or so, thus overshoot should already be extremely rare (well, I thought 99.5% is rare too). So now this should be good without extra UI noise. What do you think?

I propose we merge the linked PR and include this fix in 5.0.1, close this issue and re-open it if something does not work again. Please someone review the fix.

**Comment by Slesarew** [comment]
I've noticed another thing: since scanning and parsing are done in parallel, counter may overshoot for arbitrary number of frames if decoding is still in progress while frames keep collecting. If this is happening, I don't think we need any real fix here - frames are indeed captures, and user has no way to perform any actions in process.
Thus, maybe we should just add a short explanatory text on the bottom that explains that required frame count is only an estimate for fountain code and slightly more or less may be needed?

**Comment by goldsteinsveta** [comment]
Here's another option, just different wording to make status less strange

<img width="320" alt="ContextMenu - Key" src="https://user-images.githubusercontent.com/8782596/153383145-795ceb5b-f731-4704-8c02-8343a17fd644.png">
