### ISSUE TITLE
Parsing Error Metadata differs

### ISSUE THREAD

**Issue by Malte0815** [paritytech/parity-signer#940]
Hi,

I am getting the following error. How can I fix that?
I am using iPhone (Parity Signer Version 5) and wanted to sign a transaction in Singular Marketplace.
Error on the phone after scanning the QR-Code in the Polkadot-JS-Wallet-Browser-Extension:

All parsing attempts failed with following
errors. Parsing with kusama9151 metadata:
Network spec version decoded from
extensions (9170) differs from the version
in metadata (9151). Parsing with
Error! kusama9150 metadata: Network spec
version decoded from extensions (9170)
differs from the version in metadata (9150).
Parsing with kusama9130 metadata:
Network spec version decoded from
extensions (9170) differs from the version
in metadata (9130).

Thanks in advance, Mario.

**Comment by Slesarew** [comment]
Hi! This is clearly documentation issue, I've just pushed fix to master yesterday, so I'll close it with next release (soon). The fix makes Signer hint you at what to do in this case above the same message.

What you observe is that the network you are using (Kusama) was updated since your Signer was last synchronized with up-to-date networks (which was probably at install time). To fix this, you need to download video QR update. Update for Kusama is available at https://metadata.parity.io/#/kusama

**Comment by Malte0815** [comment]
Thanks for the quick response!
It is working now after the video QR update.
Keep up the good work. Cheers, Mario.
